[[shards]]
locationName = "Location#1"
shardID = 0
addressPort = "127.0.0.2:8080"
replicaPort = ["127.0.0.22:8080"]

[[shards]]
locationName = "Location#2"
shardID = 1
addressPort = "127.0.0.3:8080"
replicaPort = ["127.0.0.33:8080"]

[[shards]]
locationName = "Location#3"
shardID = 2
addressPort = "127.0.0.4:8080"
replicaPort = ["127.0.0.44:8080"]

[[shards]]
locationName = "Location#1"
shardID = 3
addressPort = "127.0.0.5:8080"
replicaPort = ["127.0.0.55:8080"]

